import {randomBytes,createHash,pbkdf2 as pbkdf2cb,timingSafeEqual} from 'node:crypto';
import {promisify} from 'node:util';
import {zipSync,strToU8} from 'fflate';
import {domain,fail,day,shift,validate,ledger,scenario,preemption,missing} from './core.mjs';
import {filingHTML,draftText} from './paperwork.mjs';
import {transaction,audit,record,save} from './db.mjs';
const pbkdf2=promisify(pbkdf2cb);
export const id=()=>randomBytes(12).toString('hex');
const token=()=>randomBytes(32).toString('base64url');
const digest=s=>createHash('sha256').update(s).digest('hex');
export async function password(secret,salt){return (await pbkdf2(secret,Buffer.from(salt,'hex'),600000,32,'sha256')).toString('hex')}
export function equal(a,b){return typeof a==='string'&&typeof b==='string'&&a.length===b.length&&timingSafeEqual(Buffer.from(a),Buffer.from(b))}
function response(data,status=200,type='application/json; charset=utf-8',extras={}){const raw=type.startsWith('application/json')?JSON.stringify(data):data;return new Response(raw,{status,headers:{'Content-Type':type,'Cache-Control':'no-store','X-Content-Type-Options':'nosniff','X-Frame-Options':'DENY','Content-Security-Policy':"default-src 'self'; script-src 'self'; style-src 'self'; connect-src 'self'; img-src 'self' data:; frame-ancestors 'none'; base-uri 'none'; form-action 'self'",...extras}})}
function cookie(req,value,age=28800){return `sg_session=${value}; HttpOnly; SameSite=Strict; Path=/; Max-Age=${age}${new URL(req.url).protocol==='https:'?'; Secure':''}`}
async function json(req){const b=await req.arrayBuffer();if(b.byteLength>512000)fail('요청 크기 초과',413);try{const p=JSON.parse(Buffer.from(b).toString());if(!p||typeof p!=='object'||Array.isArray(p))throw Error();return p}catch{fail('요청 자료를 확인하세요.')}}
export function createHandler(services){return async function handle(req,context={}){try{const url=new URL(req.url),path=url.pathname,method=req.method;if(!['GET','POST'].includes(method))return response({error:'허용되지 않는 요청'},405);if(method==='POST')services.verifyOrigin(req);if(path==='/api/register')return response({error:'관리자 전용 서비스입니다. 공개 가입은 비활성화되어 있습니다.'},403);
const sid=(req.headers.get('cookie')||'').split(';').map(x=>x.trim()).find(x=>x.startsWith('sg_session='))?.slice(11)||'';
if(!sid&&path!=='/api/login'&&path!=='/health'&&path!=='/api/identity/login')return response({error:'로그인이 필요합니다.'},401);
const pool=await services.pool();await services.ensure(pool);
if(path==='/health'&&method==='GET'){await pool.query('SELECT 1');return response({status:'ok',runtime:'netlify-functions',storage:'postgres+blobs'})}
if(path==='/api/login'&&method==='POST'){const p=await json(req),username=String(p.username??'').trim(),secret=String(p.password??'');if(!username||username.length>80||!secret||secret.length>200)fail('로그인 정보를 확인하세요.');
const ip=context.ip||'unknown',limitKey=digest(ip);const limits=await pool.query(`INSERT INTO sg_login_limits(key,attempts) VALUES($1,1) ON CONFLICT(key) DO UPDATE SET attempts=CASE WHEN sg_login_limits.window_start<now()-interval '15 minutes' THEN 1 ELSE sg_login_limits.attempts+1 END,window_start=CASE WHEN sg_login_limits.window_start<now()-interval '15 minutes' THEN now() ELSE sg_login_limits.window_start END RETURNING attempts`,[limitKey]);if(limits.rows[0].attempts>20)return response({error:'로그인 시도가 많습니다. 15분 후 다시 시도하세요.'},429);
let user=(await pool.query('SELECT * FROM sg_users WHERE username=$1',[username])).rows[0];
const adminName=services.env('SONG_GUARD_ADMIN_USERNAME')||'song',configured=services.env('SONG_GUARD_ADMIN_PASSWORD_HASH');if(!user&&username===adminName&&configured){const [salt,hash]=configured.split('$');if(!/^[a-f0-9]{32}$/.test(salt||'')||!/^[a-f0-9]{64}$/.test(hash||''))fail('관리자 비밀 설정을 확인하세요.',503);await pool.query('INSERT INTO sg_users(id,username,salt,password) VALUES($1,$2,$3,$4) ON CONFLICT(username) DO NOTHING',[id(),username,salt,hash]);user=(await pool.query('SELECT * FROM sg_users WHERE username=$1',[username])).rows[0]}
if(!user&&!configured)fail('관리자 계정 비밀 설정이 아직 완료되지 않았습니다.',503);
const valid=equal(await password(secret,user?.salt||'00'.repeat(16)),user?.password||'0'.repeat(64));if(!user||!valid)return response({error:'로그인 정보를 확인하세요.'},401);
const raw=token(),csrf=token();await pool.query('DELETE FROM sg_sessions WHERE expires<now()');await pool.query("INSERT INTO sg_sessions(token,user_id,csrf,expires) VALUES($1,$2,$3,now()+interval '8 hours')",[digest(raw),user.id,csrf]);return response({csrf},200,undefined,{'Set-Cookie':cookie(req,raw)})}
if(path==='/api/identity/login'&&method==='POST'){if(services.env('SONG_GUARD_IDENTITY_ENABLED')!=='true')return response({error:'Identity 로그인이 활성화되지 않았습니다.'},403);const p=await json(req);await services.identityLogin(p.email,p.password);const user=await services.identityUser();if(!user?.roles?.includes('admin')){await services.identityLogout();return response({error:'관리자 권한이 필요합니다.'},403)}const uid='identity:'+user.id;await pool.query('INSERT INTO sg_users(id,username,salt,password) VALUES($1,$2,$3,$4) ON CONFLICT(id) DO NOTHING',[uid,uid,'00'.repeat(16),'0'.repeat(64)]);const raw=token(),csrf=token();await pool.query("INSERT INTO sg_sessions(token,user_id,csrf,expires) VALUES($1,$2,$3,now()+interval '8 hours')",[digest(raw),uid,csrf]);return response({csrf},200,undefined,{'Set-Cookie':cookie(req,raw)})}
const s=(await pool.query('SELECT * FROM sg_sessions WHERE token=$1 AND expires>now()',[digest(sid)])).rows[0];if(!s)return response({error:'로그인이 필요합니다.'},401);const uid=s.user_id;
if(uid.startsWith('identity:')){const user=await services.identityUser();if(!user?.roles?.includes('admin')||'identity:'+user.id!==uid)return response({error:'관리자 권한을 확인하세요.'},403)}
if(method==='POST'&&!equal(req.headers.get('X-CSRF-Token')||'',s.csrf))return response({error:'인증 토큰을 확인하세요.'},403);
if(path==='/api/state'&&method==='GET'){const data=await transaction(pool,uid,async c=>{const records=(await c.query('SELECT id,kind,payload,version FROM sg_records WHERE user_id=$1 ORDER BY id',[uid])).rows;const logs=(await c.query('SELECT at,action,record_id FROM sg_audit WHERE user_id=$1 ORDER BY id DESC LIMIT 100',[uid])).rows;const evidence=(await c.query('SELECT id,record_id,name FROM sg_evidence WHERE user_id=$1 ORDER BY id',[uid])).rows;return {records,audit:logs.map(x=>({...x,at:new Date(x.at).toISOString()})),evidence}},{readOnly:true});data.records=data.records.filter(r=>{if(r.kind!=='task'||!r.payload.tax_id)return true;const t=data.records.find(t=>t.id===r.payload.tax_id&&t.kind==='tax')?.payload;return t?.role==='본인 납부'&&t.due_confirmed===true&&t.due&&t.due_evidence&&t.status!=='예상'&&r.payload.due===t.due});return response({...data,csrf:s.csrf,variables:domain.variables,stages:domain.stages,forms:domain.forms,connectors:{court:'사람이 출력서류 접수 · 접수증 등록',registry:'미연동 · 등기 원문 등록',bank:'미연동 · 입금 증빙 등록'}})}
if(path==='/api/logout'&&method==='POST'){await pool.query('DELETE FROM sg_sessions WHERE token=$1',[s.token]);if(uid.startsWith('identity:'))await services.identityLogout();return response({},200,undefined,{'Set-Cookie':cookie(req,'',0)})}
if(['/api/calculate','/api/scenario','/api/preemption'].includes(path)&&method==='POST'){const p=await json(req);return response({result:({'/api/calculate':ledger,'/api/scenario':scenario,'/api/preemption':preemption})[path](p)})}
if(path.startsWith('/api/print/')&&method==='GET'){const r=await record(pool,uid,path.split('/').at(-1),'filing');if(!r)return response({error:'접수서류 없음'},404);return response(filingHTML({...r.payload,id:r.id}),200,'text/html; charset=utf-8')}
if(path.startsWith('/api/draft/')&&method==='GET'){const r=await record(pool,uid,path.split('/').at(-1),'case');if(!r)return response({error:'사건 없음'},404);const claim=await record(pool,uid,r.payload.claim_id||''),asset=await record(pool,uid,r.payload.asset_id||'');return response(draftText(url.searchParams.get('kind')||'statement',r.payload,claim?.payload||{},asset?.payload||{}),200,'text/plain; charset=utf-8',{'Content-Disposition':'attachment; filename="Song_Guard_draft.txt"'})}
if(path==='/api/record'&&method==='POST'){const p=await json(req),kind=p.kind,data=p.payload,rid=p.id||id();validate(kind,data);await transaction(pool,uid,async c=>{const old=await record(c,uid,rid);if(p.id&&!old)fail('자료 없음',404);if(old?.kind==='task'&&old.payload.tax_id)fail('세금 납부기한은 세금 고지 메뉴에서 수정하세요.');if(old&&(p.version!==old.version||old.kind!==kind))fail('자료가 변경되었습니다. 새로고침 후 다시 저장하세요.',409);for(const k of ['claim_id','asset_id','case_id'])if(data[k]&&!await record(c,uid,data[k],k.replace('_id','')))fail('연결 자료 유형이 맞지 않거나 접근할 수 없습니다.');for(const k of ['evidence','completion_evidence','due_evidence'])if(data[k]){const e=(await c.query('SELECT record_id FROM sg_evidence WHERE id=$1 AND user_id=$2',[data[k],uid])).rows[0];if(!e)fail('증빙 파일을 먼저 업로드하세요.');if(['completion_evidence','due_evidence'].includes(k)&&e.record_id!==rid)fail('확인 증빙은 해당 자료에 연결되어야 합니다.')}
await save(c,uid,rid,kind,data);await audit(c,uid,old?'수정':'등록',rid);
if(kind==='tax'){const tid=digest(uid+rid+'tax-due').slice(0,24),done=['납부완료','취소확인'].includes(data.status);if(data.role==='본인 납부'&&data.due_confirmed===true&&data.due&&data.due_evidence&&data.status!=='예상'){await save(c,uid,tid,'task',{title:'확인된 세금 납부기한 · '+data.title,due:data.due,case_id:data.case_id||'',done,evidence:done?data.completion_evidence:'',tax_id:rid,automated:true,notes:'원문과 대조한 실제 납부기한: '+data.due+'. 기한 확인 증빙: '+data.due_evidence+'. 연장·분납 변경은 새 원문으로 다시 확인하세요.'});}else{await c.query('DELETE FROM sg_records WHERE id=$1 AND user_id=$2',[tid,uid]);}await audit(c,uid,'확인된 세금 납부기한 갱신',tid)}
if(kind==='case')for(const [key,label,lead] of [['auction_date','직접 입찰·공유자 우선매수 검토',7],['distribution_date','배당표·채권액·수령 요건 검토',3],['claim_deadline','채권신고·배당요구 필요 여부 및 제출 확인',3],['special_deadline','채권자 매수 특별지급 신고 검토',1]]){const tid=digest(uid+rid+key).slice(0,24),previous=await record(c,uid,tid);if(previous?.payload.done)continue;if(!data[key]){if(previous){await c.query('DELETE FROM sg_records WHERE id=$1 AND user_id=$2',[tid,uid]);await audit(c,uid,'자동 업무 기일 해제',tid)}continue}const task={title:label,due:shift(data[key],-lead),case_id:rid,done:false,notes:'자동 준비일. 원문 기한: '+data[key]+'. 등록 기일의 정확성과 변경 여부를 확인하세요.',source_date:data[key],automated:true};await save(c,uid,tid,'task',task);await audit(c,uid,'사건 기일 준비업무 갱신',tid)}
if(kind==='event'&&!old){const category=data.category||'미분류 변수',actions=domain.variables[category]||domain.variables['미분류 변수'],tid=id(),task={title:category+' 검토',due:data.due,case_id:data.case_id||'',notes:actions.join(' / '),done:false};validate('task',task);await save(c,uid,tid,'task',task);await audit(c,uid,'변수 대응업무 생성',tid)}});return response({id:rid})}
if(path==='/api/filing'&&method==='POST'){const p=await json(req),rid=p.id||id();await transaction(pool,uid,async c=>{const old=await record(c,uid,rid,'filing');if(p.id&&!old)fail('접수서류 없음',404);if(old&&p.version!==old.version)fail('서류가 변경되었습니다. 새로고침하세요.',409);let doc=old?.payload||{};switch(p.action){case 'save':{if(old&&doc.status!=='작성중')fail('확정된 문서는 수정할 수 없습니다. 새 문서를 생성하세요.');const kind=p.form_kind,form=domain.forms[kind];if(!form||!p.data||typeof p.data!=='object'||Array.isArray(p.data))fail('잘못된 서식');if(Buffer.byteLength(JSON.stringify(p.data))>100000)fail('서류 크기 초과');const data=Object.fromEntries(form.fields.filter(f=>p.data[f.key]!==undefined).map(f=>[f.key,String(p.data[f.key])])),caseRow=await record(c,uid,p.case_id,'case');if(!caseRow)fail('연결 경매사건을 선택하세요.');const snapshot={case:caseRow};for(const k of ['claim','asset']){const source=await record(c,uid,caseRow.payload[k+'_id']||'',k);if(source)snapshot[k]=source}doc={title:form.title,form_kind:kind,case_id:p.case_id,data,status:'작성중',checks:{},snapshot};break}
case 'approve':{if(doc.status!=='작성중')fail('작성중 문서만 확정할 수 있습니다.');const errors=missing(doc.form_kind,doc.data);if(errors.length)fail('필수 입력 확인: '+errors.join(', '));if(Object.keys(domain.checks).some(k=>p.checks?.[k]!==true))fail('제출 전 확인사항을 모두 확인하세요.');if(doc.form_kind==='petition'&&doc.snapshot.asset?.payload.ownership!=='근저당')fail('이 임의경매 서식은 근저당 실행용입니다. 지분이전·가등기담보는 별도 검토하세요.');if(doc.form_kind==='preemption'&&(doc.snapshot.case.payload.type!=='share'||doc.snapshot.asset?.payload.ownership!=='공유지분 소유'))fail('타인 지분 매각 및 등기상 공유자 지위를 확인한 공유지분 자산을 연결하세요.');Object.assign(doc,{status:'출력준비',checks:p.checks,approved_at:Date.now()/1000});break}
case 'printed':if(doc.status!=='출력준비'||p.confirmed!==true)fail('확정된 실제 출력본 확인이 필요합니다.');Object.assign(doc,{status:'출력확인',printed_at:Date.now()/1000});break;
case 'submit':{if(doc.status!=='출력확인')fail('출력·서명·첨부 준비를 확인한 뒤 접수를 등록하세요.');const r=p.receipt||{};day(r.date);if(r.signed!==true||!r.number||!r.by)fail('서명·첨부, 접수번호와 접수자를 확인하세요.');const proof=(await c.query('SELECT 1 FROM sg_evidence WHERE id=$1 AND user_id=$2 AND record_id=$3',[r.evidence||'',uid,doc.case_id])).rows[0];if(!proof)fail('해당 사건에 접수증 증빙을 먼저 업로드하세요.');Object.assign(doc,{status:'접수완료',receipt:Object.fromEntries(['date','number','by','evidence','notes','case_number'].map(k=>[k,r[k]||'']))});if(doc.form_kind==='petition'){const cr=await record(c,uid,doc.case_id,'case');if(!cr)fail('연결 사건 없음');const data=cr.payload;if(['관리','집행준비'].includes(data.stage))data.stage='경매접수';if(r.case_number)data.number=r.case_number;await save(c,uid,cr.id,'case',data);await audit(c,uid,'사람 접수 확인 후 사건 갱신',cr.id)}const tid=id();await save(c,uid,tid,'task',{title:doc.title+' 접수 후 진행·보정 안내 확인',due:shift(r.date,7),case_id:doc.case_id,done:false,notes:'접수 7일 후 내부 확인일입니다. 법정기한이 아니며 법원 통지의 실제 기한을 별도 등록하세요.'});await audit(c,uid,'접수 후 확인업무 생성',tid);break}
default:fail('지원되지 않는 접수 작업')}
await save(c,uid,rid,'filing',doc);await audit(c,uid,'접수서류 '+p.action,rid)});return response({id:rid})}
if(path.startsWith('/api/upload/')&&method==='POST'){const rid=path.split('/').at(-1);if(!await record(pool,uid,rid))return response({error:'자료 없음'},404);const raw=new Uint8Array(await req.arrayBuffer());if(!raw.length)fail('빈 파일');if(raw.length>4*1024*1024)fail('첨부파일은 최대 4MB입니다.',413);const eid=id(),name=(req.headers.get('X-File-Name')||'evidence').slice(0,200);try{decodeURIComponent(name)}catch{fail('파일명을 확인하세요.')}const namespace=context.deploy?.context==='production'?'production':'preview-'+(context.deploy?.id||'local'),key=namespace+'/'+uid+'/'+eid;const blobs=services.blobs();await blobs.set(key,raw.buffer);try{await transaction(pool,uid,async c=>{if(!await record(c,uid,rid))fail('자료 없음',404);await c.query('INSERT INTO sg_evidence(id,user_id,record_id,name,blob_key,size) VALUES($1,$2,$3,$4,$5,$6)',[eid,uid,rid,name,key,raw.length]);await audit(c,uid,'증빙 업로드',rid)})}catch(e){await blobs.delete(key).catch(()=>{});throw e}return response({id:eid})}
if(path.startsWith('/api/evidence/')&&method==='GET'){const e=(await pool.query('SELECT blob_key FROM sg_evidence WHERE id=$1 AND user_id=$2',[path.split('/').at(-1),uid])).rows[0];if(!e)return response({error:'자료 없음'},404);const raw=await services.blobs().get(e.blob_key,{type:'stream'});if(!raw)fail('저장된 증빙을 찾을 수 없습니다.',503);return response(raw,200,'application/octet-stream',{'Content-Disposition':'attachment; filename="evidence.bin"'})}
if(path==='/api/export'&&method==='GET'){const data=await transaction(pool,uid,async c=>({records:(await c.query('SELECT id,kind,payload,version FROM sg_records WHERE user_id=$1',[uid])).rows,audit:(await c.query('SELECT at,action,record_id FROM sg_audit WHERE user_id=$1 ORDER BY id',[uid])).rows,evidence:(await c.query('SELECT id,blob_key,size FROM sg_evidence WHERE user_id=$1',[uid])).rows}),{readOnly:true});if(data.evidence.reduce((n,e)=>n+e.size,0)>16*1024*1024)fail('내보내기 첨부 합계가 16MB를 초과합니다. 원문은 개별 다운로드하세요.',413);const files={'records.json':strToU8(JSON.stringify(data.records,null,2)),'audit.json':strToU8(JSON.stringify(data.audit,null,2))};for(const e of data.evidence){const raw=await services.blobs().get(e.blob_key,{type:'arrayBuffer'});if(!raw)fail('내보내기 증빙 원문이 누락되었습니다.',503);files['evidence/'+e.id]=new Uint8Array(raw)}const zipped=zipSync(files);if(zipped.length>18*1024*1024)fail('내보내기 크기 초과. 증빙을 개별 다운로드하세요.',413);const stream=new ReadableStream({start(controller){for(let i=0;i<zipped.length;i+=65536)controller.enqueue(zipped.slice(i,i+65536));controller.close()}});return response(stream,200,'application/zip',{'Content-Disposition':'attachment; filename="Song_Guard_export.zip"'})}
return response({error:'지원되지 않는 경로'},404)
}catch(e){const status=e.status||(e.name==='MissingDatabaseConnectionError'?503:0)||(e.code==='40001'||e.code==='40P01'?409:e.code==='23505'?409:500);if(status===500)console.error('SongGuard request failed',e.code||e.name);return response({error:status===500?'저장소 연결 또는 처리 오류입니다. Netlify 데이터베이스 설정을 확인하세요.':e.name==='MissingDatabaseConnectionError'?'Netlify Database 연결을 확인하세요.':status===409?'자료가 변경되었습니다. 새로고침 후 다시 시도하세요.':e.message},status)}}}
