import Decimal from 'decimal.js';
import domain from './domain.json' with {type:'json'};
export {domain};
Decimal.set({precision:28,rounding:Decimal.ROUND_HALF_EVEN});
export function fail(message,status=400){const e=new Error(message);e.status=status;throw e}
export function day(s){if(typeof s!=='string'||!/^\d{4}-\d{2}-\d{2}$/.test(s)||s.startsWith('0000'))fail('날짜 형식을 확인하세요.');const n=Date.parse(s+'T00:00:00Z');if(!Number.isFinite(n)||new Date(n).toISOString().slice(0,10)!==s)fail('유효한 날짜를 입력하세요.');return n/86400000}
export const shift=(s,n)=>new Date((day(s)+n)*86400000).toISOString().slice(0,10);
export function money(v=0){let n;try{n=new Decimal(String(v))}catch{fail('금액 입력을 확인하세요.')}if(!n.isFinite()||n.isNegative()||n.gt(Number.MAX_SAFE_INTEGER))fail('금액은 안전한 범위의 0 이상 유한한 값이어야 합니다.');return n}
export function won(n){const rounded=n.toDecimalPlaces(0,Decimal.ROUND_HALF_UP);if(rounded.abs().gt(Number.MAX_SAFE_INTEGER))fail('금액 범위를 초과했습니다.');return rounded.toNumber()}
export function ledger(c){let principal=money(c.principal),interest=new Decimal(0),costs=money(c.costs??0);const start=day(c.start),end=day(c.as_of);if(end<start)fail('기준일은 대여일 이후여야 합니다.');const rate=money(c.rate??0).div(100);if(rate.gt(1))fail('이율 입력을 확인하세요.');if(!Array.isArray(c.payments??[]))fail('변제내역은 배열이어야 합니다.');let cursor=start;const rows=[];for(const p of [...(c.payments??[])].sort((a,b)=>String(a.date).localeCompare(String(b.date)))){const d=day(p.date);if(d<start||d>end)fail('변제일이 계산기간 밖입니다.');interest=interest.plus(principal.times(rate).times(d-cursor).div(365));let amount=money(p.amount),original=amount;let used=Decimal.min(amount,costs);costs=costs.minus(used);amount=amount.minus(used);used=Decimal.min(amount,interest);interest=interest.minus(used);amount=amount.minus(used);used=Decimal.min(amount,principal);principal=principal.minus(used);amount=amount.minus(used);if(amount.gt(0))fail('변제액이 계산된 채무액을 초과합니다. 별도 정산이 필요합니다.');rows.push({date:p.date,payment:won(original),principal:won(principal),interest:won(interest),costs:won(costs)});cursor=d}interest=interest.plus(principal.times(rate).times(end-cursor).div(365));const total=principal.plus(interest).plus(costs),cap=money(c.cap??total);return {principal:won(principal),interest:won(interest),costs:won(costs),total:won(total),secured_estimate:won(Decimal.min(total,cap)),rows,assumptions:'단일 연이율·365일 단리·비용→이자→원금 충당. 약정/법률상 이율·충당·담보범위 확인 후 사용.'}}
export function scenario(c){const m=k=>money(c[k]??0),price=m('price'),claim=m('claim'),cap=m('cap'),deposit=m('deposit');if(deposit.gt(price))fail('보증금은 매수가격을 초과할 수 없습니다.');const dividend=Decimal.min(Decimal.max(0,price.minus(m('priority')).minus(m('execution'))),claim,cap),extra=m('taxes').plus(m('holding')).plus(m('repair')).plus(m('sale_cost')),value=m('resale');return {dividend:won(dividend),shortfall:won(Decimal.max(0,claim.minus(dividend))),cash_normal:won(price.plus(extra)),cash_with_special_payment:won(price.minus(dividend).plus(extra)),remaining_normal:won(price.minus(deposit)),remaining_special:won(Decimal.max(0,price.minus(dividend).minus(deposit))),asset_net_value:won(value.minus(extra)),economic_recovery:won(value.minus(price).minus(extra).plus(dividend)),assumptions:'입력한 선순위 금액과 담보한도를 적용한 단일 물건 추정. 실제 배당·세액·인수권리 확정 아님. 특별지급은 자격·기한·이의 확인 필요.'}}
export function preemption(c){if(c.type!=='share')return {status:'review',message:'전체매각·공유물분할·일괄매각은 우선매수 적용을 별도 검토하세요.'};if(c.coowner_verified!==true||c.other_share_verified!==true)return {status:'review',message:'본인의 공유자 지위와 다른 공유자 지분 매각 여부를 등기로 확인하세요.'};return {status:'candidate',message:'우선매수 검토 대상입니다. 민사집행법 제140조상 매각기일까지 보증 제공 및 최고매수신고가격과 같은 가격의 신고가 필요합니다. 사건 매각조건과 행사 제한을 확인하세요.'}}
export function validate(kind,p){if(!['claim','asset','case','task','event'].includes(kind)||!p||typeof p!=='object'||Array.isArray(p)||typeof p.title!=='string'||!p.title.trim())fail('자료 유형과 제목을 확인하세요.');if(Buffer.byteLength(JSON.stringify(p))>100000)fail('자료 크기 초과');if(kind==='claim')ledger(p);if(kind==='case'){if(!domain.stages.includes(p.stage))fail('잘못된 사건 단계');if(['전액회수','직접취득'].includes(p.stage)&&!p.completion_evidence)fail('종결 증빙이 필요합니다.');for(const k of ['auction_date','distribution_date','claim_deadline','special_deadline'])if(p[k])day(p[k]);for(const k of ['minimum','received'])if(p[k])money(p[k])}if(kind==='task'){day(p.due);if(p.done&&!p.evidence)fail('완료 증빙이 필요합니다.')}if(kind==='event'){day(p.due);if(p.occurred)day(p.occurred)}}
export function missing(kind,d){const form=domain.forms[kind];if(!form)fail('지원되지 않는 서식');const errors=form.fields.filter(f=>!String(d[f.key]??'').trim()).map(f=>f.label);for(const k of ['amount','price','dividend'])if(d[k]){try{const n=money(String(d[k]).replaceAll(',',''));if(!n.isInteger())throw Error()}catch{errors.push(k+' 금액은 0 이상의 정수로 입력하세요.')}}for(const k of ['signed_date','order_date'])if(d[k]){try{day(d[k])}catch{errors.push(k+' 날짜 형식')}}if(kind==='special'&&!errors.length&&money(d.dividend.replaceAll(',','')).gt(money(d.price.replaceAll(',',''))))errors.push('배당금액은 매수가격 이하여야 합니다.');return errors}
export const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
