import Decimal from 'decimal.js';
import {domain,esc,ledger,day} from './core.mjs';
export function filingHTML(filing){const kind=filing.form_kind,d=filing.data,approved=filing.status!=='작성중',value=k=>esc(d[k]??'미입력').replaceAll('\n','<br>'),section=(t,k)=>`<section><h2>${esc(t)}</h2><p>${value(k)}</p></section>`;let body=`<h1>${domain.titles[kind]}</h1>`;if(kind!=='petition')body+=`<p class="case">사건 ${value('number')}</p>`;body+=`<div class="parties"><p>채권자(신고인)　${value('creditor')}<br>주소　${value('creditor_address')}<br>연락처　${value('phone')}</p><p>채무자　${value('debtor')}<br>주소　${value('debtor_address')}</p>`;if(kind==='petition')body+=`<p>소유자　${value('owner')}<br>주소　${value('owner_address')}</p>`;body+='</div>';
if(kind==='petition')body+='<section><h2>신청취지</h2><p>별지 기재 부동산에 관하여 담보권 실행을 위한 경매절차를 개시하여 주시기 바랍니다.</p></section>'+section('청구금액 (원)','amount')+section('청구금액 산출내역','breakdown')+section('신청이유 - 채권의 발생','basis')+section('변제기 및 담보권 실행 사유','default_basis')+section('담보권의 표시','security')+section('담보권 실행의 취지와 범위','scope');
else if(['statement','demand'].includes(kind))body+=`<p>${kind==='statement'?'아래와 같이 채권액을 신고합니다.':'아래 채권에 관하여 배당을 요구합니다.'}</p>`+section('채권액 (원)','amount')+section('산출내역','breakdown')+section('채권 및 자격의 근거','basis');
else if(kind==='preemption')body+='<p>민사집행법 제140조에 따라 최고매수신고가격과 같은 가격으로 아래 매각 대상 지분을 우선매수하겠다는 신고를 합니다.</p>'+section('본인의 공유자 지위','share')+section('매각 대상','property')+section('보증 제공','security')+section('신고 근거','basis');
else if(kind==='special'){let difference='미확인';try{difference=new Decimal(String(d.price||0).replaceAll(',','')).minus(new Decimal(String(d.dividend||0).replaceAll(',',''))).toString()}catch{}body+='<p>민사집행법 제143조 제2항에 따라 배당받아야 할 금액을 제외한 대금을 배당기일에 지급하고자 신고합니다.</p>'+section('매수가격 (원)','price')+section('배당받아야 할 금액 (원)','dividend')+`<p>위 배당액을 제외한 금액: ${esc(difference)}원</p>`+section('기납부 보증금과 처리','security')+section('신고 자격 및 근거','basis')}
else if(kind==='correction')body+=section('보정명령일','order_date')+section('보정 내용','correction');else if(kind==='payment')body+='<p>아래 배당금의 지급을 청구합니다.</p>'+section('지급 청구액 (원)','amount')+section('수령인','payee')+section('지급 계좌','bank')+section('청구 근거','basis');
body+=section('첨부서류','attachments')+`<div class="signature"><p>${value('signed_date')}</p><p>신청·신고인　${value('creditor')}　(서명 또는 인)</p><h2>${value('court')} 귀중</h2></div>`;if(kind==='petition')body+=`<article class="appendix"><h1>별지 부동산 목록</h1><p>${value('property')}</p></article>`;
const instruction=`<article class="appendix cover"><h1>접수 준비표 · 제출 문서와 분리</h1><p>이 페이지는 본인 보관용입니다. 신청서와 구분해 보관하세요.</p><p>문서번호: ${esc(filing.id)}</p><ol>${Object.values(domain.checks).map(v=>`<li>${esc(v)}</li>`).join('')}</ol><p>출력 → 서명·날인 → 실제 첨부자료 준비 → 관할 법원 접수 → 접수증 보관 → Song_Guard에 접수기록 등록</p><p>접수일: __________　사건/접수번호: __________________</p><p>접수 담당자: __________　보정·후속 안내: __________________</p><p>공유자 우선매수는 사건별 보증 제공과 신고 시점 확인이 필요합니다. 특별지급은 매각결정기일 종료까지 신고하고 배당액 이의가 있는 경우 추가 납부 가능성을 확인합니다. 배당금 지급은 법원의 지정 서식과 수령자격·계좌증빙을 확인하세요.</p></article>`;
return `<!doctype html><html lang="ko"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${domain.titles[kind]}</title><link rel="stylesheet" href="/print.css"><script src="/print.js" defer></script></head><body><div class="toolbar"><strong>${esc(filing.status)}</strong><span>서명·날인과 첨부자료를 준비하여 사람이 접수합니다.</span><button id="print" ${approved?'':'disabled'}>인쇄 / PDF 저장</button><button id="back">이전 화면</button></div>${approved?'':'<div class="warning">작성중 문서입니다. 필수 항목과 확인사항을 완료한 뒤 출력본을 확정하세요.</div>'}<article class="document">${body}</article>${instruction}</body></html>`}
export function draftText(kind,caseData,claim,asset){const title=domain.titles[kind];if(!['petition','statement','preemption','special'].includes(kind))throw Error('지원되지 않는 문서 종류');const amount=Object.keys(claim).length?ledger(claim):null;return `[제출 전 검토용 초안 · 자동 접수되지 않음]\n${title} 초안\n사건: ${caseData.number||'[확인 필요]'}\n법원: ${caseData.court||'[확인 필요]'}\n채권자: ${claim.creditor||'[확인 필요]'}\n채무자: ${claim.debtor||'[확인 필요]'}\n부동산 표시: ${asset.legal_description||'[확인 필요]'}\n담보권: ${asset.rank||'[확인 필요]'}\n\n연결 자료\n${JSON.stringify({case:caseData,claim,asset,calculation:amount},null,2)}\n\n정식 출력서류는 서류 생성 · 접수 화면에서 작성하고 확정하세요. 공유자 지위·매각조건·신고 자격·기한·보증 및 최신 법원 서식 검토가 필요합니다.\n`}
